# Domain configuration (place your domain here)
domainName: "example.com"

# Nginx configuration to proxy requests into the deployment
nginx:
  replicaCount: 1
  enableSSL: true
  # IPv4 ranges(These cover Cloudflare so only CF can interact with your back-end for requests less strain way less ddos)
  cloudflareAllowlist:
    - "103.21.244.0/22"
    - "103.22.200.0/22"
    - "103.31.4.0/22"
    - "104.16.0.0/13"
    - "104.24.0.0/14"
    - "108.162.192.0/18"
    - "131.0.72.0/22"
    - "141.101.64.0/18"
    - "162.158.0.0/15"
    - "172.64.0.0/13"
    - "173.245.48.0/20"
    - "188.114.96.0/20"
    - "190.93.240.0/20"
    - "197.234.240.0/22"
    - "198.41.128.0/17"
  # IPv6 ranges(These cover Cloudflare so only CF can interact with your back-end for requests less strain way less ddos)
  cloudflareAllowlistIPv6:
    - "2400:cb00::/32"
    - "2606:4700::/32"
    - "2803:f800::/32"
    - "2405:b500::/32"
    - "2405:8100::/32"
    - "2a06:98c0::/29"
    - "2c0f:f248::/32"

# WordPress configuration
wordpress:
  image: bitnami/wordpress-nginx:latest
  replicas: 1
  resources:
    limits:
      memory: "4Gi" #Base Configuration change as you desire
      cpu: "2" #Base Configuration change as you desire
    requests:
      memory: "2Gi" #Base Configuration change as you desire
      cpu: "1" #Base Configuration change as you desire
  persistence:
    enabled: true
    storageSize: 10Gi #Base Configuration change as you desire
    storageClass: local-path
  env:
    WORDPRESS_DATABASE_NAME: "wordpress_db" #Base Configuration change as you desire
    WORDPRESS_TABLE_PREFIX: "wp_" #Base Configuration change as you desire
    WORDPRESS_DATABASE_HOST: "mysql-svc" #Base Configuration change as you desire
    WORDPRESS_DATABASE_PORT_NUMBER: "3306" #Base Configuration change as you desire
    WORDPRESS_DATABASE_USER: "wordpress_user" #Base Configuration change as you desire
    WORDPRESS_ENABLE_REVERSE_PROXY: "yes"
    WORDPRESS_ENABLE_HTTPS: "yes"
    WORDPRESS_BLOG_NAME: "Example blog" #Base Configuration change as you desire

# Database configuration
database:
  image: mysql:8.0 #Tested with 8.0 change this with your knowledge of the versions.
  host: mysql-svc 
  name: wordpress_db #Change accordingly
  user: wordpress_user #Change accordingly
  password: "ZXhhbXBsZV9wYXNzd29yZA=="  # example_password (base64 encoded)
  rootPassword: "ZXhhbXBsZV9yb290X3Bhc3N3b3Jk"  # example_root_password (base64 encoded)
  storageSize: 10Gi #Base Configuration change as you desire
  storageClass: local-path
  resources:
    limits:
      memory: "6Gi" #Base Configuration change as you desire
      cpu: "2" #Base Configuration change as you desire
    requests:
      memory: "3Gi" #Base Configuration change as you desire
      cpu: "1.5" #Base Configuration change as you desire
# Cloudflare configuration
cloudflare:
  email: "example@mail.com" #Your domain
  tunnelId: "some-random-tunnel-id" #Your tunnelID
  credentialsSecret: "cloudflare-tunnel-credentials"
  credentialsFile: "credentials.json"
#FOLLOW THE README.MD for this part!!!