apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql
    {{- include "wordpress-helm.labels" . | nindent 4 }}
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.database.image }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
        env:
        - name: MYSQL_DATABASE
          value: {{ .Values.database.name }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: mysql-root-password
        - name: MYSQL_USER
          value: {{ .Values.database.user }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: mysql-password
        resources:
          limits:
            memory: {{ .Values.database.resources.limits.memory }}
            cpu: {{ .Values.database.resources.limits.cpu }}
          requests:
            memory: {{ .Values.database.resources.requests.memory }}
            cpu: {{ .Values.database.resources.requests.cpu }}
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.database.storageClass }}
      resources:
        requests:
          storage: {{ .Values.database.storageSize }}