apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress-helm.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    events {}

    http {
        server {
            listen 80;
            server_name {{ .Values.domainName }} *.{{ .Values.domainName }};
            
            # Block xmlrpc.php
            location = /xmlrpc.php {
                return 404;
            }

            {{- range .Values.nginx.cloudflareAllowlist }}
            allow {{ . }};
            {{- end }}
            
            {{- range .Values.nginx.cloudflareAllowlistIPv6 }}
            allow {{ . }};
            {{- end }}
            
            # Deny all other IPs
            deny all;
            
            # Since we're using Cloudflare tunnel, we don't need redirect
            # Just proxy to WordPress directly
            location / {
                proxy_pass http://wordpress-svc:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
            }
        }
    }