# Cloudflare Tunnel Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.cloudflare.credentialsSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress-helm.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Files.Get (printf "cloudflare/%s" .Values.cloudflare.credentialsFile) | b64enc }}
---
# MySQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress-helm.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.database.rootPassword | b64enc }}
  mysql-password: {{ .Values.database.password }}
---
# WordPress Secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wordpress-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress-helm.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.database.password }}