# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql
    {{- include "wordpress-helm.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-mysql
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
---
# WordPress Service
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: wordpress
    {{- include "wordpress-helm.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-wordpress
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 8443
    targetPort: 8443
    name: https